name: Repo visualizer

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Update diagram
      uses: githubocto/repo-visualizer@main
      with:
        should_push: false
        output_file: 'diagram.svg'
        artifact_name: 'diagram'
        excluded_paths: 'dist,node_modules,vcpkg'
